### PR TITLE
Simplify Dockerfile

### PR DESCRIPTION
**Pull request by morganchristiansson**

### CODE REVIEW

**Comment by loopingz** [comment]
This simplification will prevent the build on Docker hub because when you clone the repo by default it has no .jar in the target folder

**Comment by morganchristiansson** [comment]
Oh... it builds on dockerhub - I've never tried that

**Comment by morganchristiansson** [comment]
So it could be solved by custom build hooks and kept out of main container build.. https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands

But it's fine as is for now...

**Comment by morganchristiansson** [comment]
So the build hooks are only supported when using docker cloud builds and not when using docker hub builds.

A smaller image size can be achieved by removing uncessecary layers. 90.8MB instead of current 115MB. A saving of 25MB. Using openjdk:8-jre-alpine base image.

**Comment by loopingz** [comment]
Once build we can also remove the source and probably the Maven cache

**Comment by morganchristiansson** [comment]
Yeah. just need to make it a giant chain of && commands as is common in Dockerfiles.. The bigger gain is from using smaller base image though I think. The difference is not big but it's nice to have smaller base image.

**Comment by morganchristiansson** [comment]
Though it could be that downloaded dependencies and build arefacts add a chunk to the image...

**Comment by morganchristiansson** [comment]
Resubmitted as #10

**Pull request closed without merging**
